renturcar/adminapp/urls.py
from django.conf.urls import url
from views.login_view import LoginView
from .views.login_view import LogoutView
from .views.dashboard_view import DashboardView
from .views.admin_view import AdminCreate,AdminList,AdminDelete,AdminUpdate,AdminProfileUpdate,AdminPasswordChange
from django.contrib.auth.decorators import login_required
from .views.user_view import UserView,UserDetailView,UserApprove,UserDelete,UserCreateView
from .views.car_view import CarView,CarDetailView,CarApprove,CarDelete,CarCreateView
from .views.report_view import ReportCarView,ReportDailyUpdateView
urlpatterns = [

    # url(r'^admin/', admin.site.urls),
    url(r'^$',  LoginView.as_view()),
    url(r'^logout/$',  LogoutView.as_view(),name="logout"),
    url(r'^dashboard/$',login_required(DashboardView.as_view()),name="dashboard"),
    url(r'^add-admin/$',login_required(AdminCreate.as_view()),name="add-admin"),
    url(r'^list-admin/$',login_required(AdminList.as_view()),name="list-admin"),
    url(r'^delete-admin/(?P<id>[0-9]+)/$',login_required(AdminDelete.as_view()),name="delete-admin"),
    url(r'^update-admin/(?P<id>[0-9]+)/$',login_required(AdminUpdate.as_view()),name="update-admin"),
    url(r'^update-profile/$',login_required(AdminProfileUpdate.as_view()),name="update-profile"),
    url(r'^change-password/$',login_required(AdminPasswordChange.as_view()),name="change-password"),

    # user
    url(r'^user/(?P<status>[\w-]+)/$',login_required(UserView.as_view()),name="user"),
    url(r'^user/details/(?P<id>[0-9]+)/$',login_required(UserDetailView.as_view()),name="user-details"),
    url(r'^user-approve/$',login_required(UserApprove.as_view()),name="user-approve"),
    url(r'^delete-user/(?P<id>[0-9]+)/$', login_required(UserDelete.as_view()),name="delete-user"),
    url(r'^add-user/$',login_required(UserCreateView.as_view()),name="add-user"),
    #car
    url(r'^car/(?P<status>[\w-]+)/$',login_required(CarView.as_view()),name="car"),
    url(r'^car/details/(?P<id>[0-9]+)/$',login_required(CarDetailView.as_view()),name="car-details"),
    url(r'^car-approve/$',login_required(CarApprove.as_view()),name="car-approve"),
    url(r'^delete-car/(?P<id>[0-9]+)/$', login_required(CarDelete.as_view()),name="delete-car"),
    url(r'^add-car/$',login_required(CarCreateView.as_view()),name="add-car"),
    #report
    url(r'^report-car-view/$',login_required(ReportCarView.as_view()),name="report-car-view"),
    url(r'^report-daily-update/$',login_required(ReportDailyUpdateView.as_view()),name="report-daily-update"),
]

renturcar/renturcar/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from api.views import *
from django.conf import settings
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include('adminapp.urls')),
    url(r'^login$', login_view),
    url(r'^logout$', logout_view),
    url(r'^signup/?$', signup_view),

    # User views.
    url(r'^user/?$', user_views),
    url(r'^user/(inbox)/?$', user_views),
    url(r'^user/inbox/with/(\w*)', user_view_inbox_direct),
    url(r'^user/message/reply', message_reply),
    url(r'^user/(cars)/?$', user_views),
    url(r'^user/(history)/?$', user_views),
    url(r'^user/verify/(.*)/(.*)?$', user_view_verify),
    url(r'^user/booking-inbox/(\w*)', user_booking_inbox),

    # User Account views.
    url(r'^user/account/?$', user_account_index_view),
    url(r'^user/account/picture/?$', user_account_picture_view),
    url(r'^user/account/licence/?$', user_account_license_view),
    url(r'^user/account/(payment)/?$', user_account_views),
    url(r'^user/account/(payout)/?$', user_account_views),
    url(r'^user/account/(security)/?$', user_account_views),
    url(r'^user/account/(cancel)/?$', user_account_views),
    url(r'^user/account/security/change-password/?$', change_password_view),
    url(r'^confirmation/?$', user_account_confirmation_view),
    url(r'^terms-and-conditions/?$', terms_and_conditions_view),




    url(r'^car/(\w*)/request/(\w*)?/?(\w*)?', car_request_view),
    url(r'^car/(\w*)/a/(.*)/(.*)', car_availability),
    url(r'^car/(\w*)/?.*', car_view, name='car_view'),

    url(r'^message', send_message_view),

    url(r'^search$', search_view, name='search_view'),

    url(r'^new$', new_listing_view, name='new_listing_view'),
    url(r'^requirements$', requirements_view),
    url(r'^contact/$', contact_view, name='contact_view'),


    url(r'^$', home_view),




]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renturcar/adminapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

renturcar/api/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db.models import Q
from django.template.defaulttags import register
from django.db.models import Avg

from datetime import datetime
import hashlib
import pendulum
import requests
import urllib2
import json
from datetime import timedelta
import smtplib
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email
        and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email
        password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    # Used to store a new email while verification of the address is pending.
    newEmail = models.EmailField(max_length=255, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    __original_newEmail = None

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    def __init__(self, *args, **kwargs):
        super(MyUser, self).__init__(*args, **kwargs)
        self.__original_newEmail = self.newEmail

    def save(self, *args, **kwargs):
        super(MyUser, self).save(*args, **kwargs)

        if self.newEmail != self.__original_newEmail:
            v = self.person.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_EMAIL
            v.save()
            self.person.emailVerification = v
            self.person.save()

        super(MyUser, self).save(*args, **kwargs)

        self.__original_newEmail = self.newEmail

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Address(models.Model):
    lineOne = models.CharField(max_length=200)
    lineTwo = models.CharField(max_length=200)
    country = models.CharField(max_length=50)
    postCode = models.CharField(max_length=30)

    def __str__(self):
        return self.lineTwo

admin.site.register(Address)

# new model admin Details

class Admin(models.Model):
    user = models.OneToOneField(MyUser)
    firstname = models.CharField(max_length=100, blank=True)
    lastname = models.CharField(max_length=100, blank=True)
    username = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField()
    role = models.CharField(max_length=100)

class Person(models.Model):
    user = models.OneToOneField(MyUser)
    dateOfBirth = models.DateField()  # Age Validation
    address = models.ForeignKey(Address, null=True, blank=True)
    phone = models.CharField(max_length=20)
    profilePicture = models.ImageField(blank=True, null=True)
    firstName = models.CharField(max_length=100, blank=True)
    lastName = models.CharField(max_length=100, blank=True)
    displayName = models.CharField(max_length=100, blank=True)
    gender = models.CharField(max_length=100, blank=True)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    __original_dateOfBirth = None
    __original_address = None
    __original_phone = None
    __original_firstName = None
    __original_lastName = None
    __original_email = None

    emailVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")
    dateOfBirthVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")
    addressVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")
    phoneNumberVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")
    firstNameVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")
    lastNameVerification = models.ForeignKey('Verification', null=True, blank=True, related_name="+")

    def __unicode__(self):
        return self.user.email

    def __init__(self, *args, **kwargs):
        super(Person, self).__init__(*args, **kwargs)
        self.__original_dateOfBirth = self.dateOfBirth
        self.__original_address = self.address
        self.__original_phone = self.phone
        self.__original_firstName = self.firstName
        self.__original_lastName = self.lastName
        # self.__original_email = self.user.email

    def default_verification_object(self):
        v = Verification()
        v.code = v.generate_code(self)
        v.expires = pendulum.now('Australia/West').add(days=7)
        v.person = self
        return v

    def save(self, *args, **kwargs):

        if self.displayName == "" and self.firstName != "":
            self.displayName = self.firstName

        super(Person, self).save(*args, **kwargs)

        if self.dateOfBirth != self.__original_dateOfBirth:
            v = self.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_DATEOFBIRTH
            v.save()
            self.dateOfBirthVerification = v

        if self.address != self.__original_address:
            v = self.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_ADDRESS
            v.save()
            self.addressVerification = v

        if self.phone != self.__original_phone:
            v = self.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_PHONE
            v.save()
            self.phoneNumberVerification = v

        if self.firstName != self.__original_firstName:
            v = self.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_NAME
            v.save()
            self.firstNameVerification = v

        if self.lastName != self.__original_lastName:
            v = self.default_verification_object()
            v.verifying = Verification.VERIFYING_CHOICE_NAME
            v.save()
            self.lastNameVerification = v

        if self.user.email != self.__original_email:
            if not self.is_email_verified():
                v = self.default_verification_object()
                v.verifying = Verification.VERIFYING_CHOICE_EMAIL
                v.save()
                self.emailVerification = v

        super(Person, self).save(*args, **kwargs)

        self.__original_dateOfBirth = self.dateOfBirth
        self.__original_address = self.address
        self.__original_phone = self.phone
        self.__original_firstName = self.firstName
        self.__original_lastName = self.lastName

    def can_rent(self):
        if not self.approved:
            return False
        if self.emailVerification and not self.emailVerification.verified:
            return False

        if self.dateOfBirthVerification and not self.dateOfBirthVerification.verified:
            return False

        # if self.addressVerification and not self.addressVerification.verified:
        #     return False

        # if self.phoneNumberVerification and not self.phoneNumberVerification.verified:
        #     return False

        if self.firstNameVerification and not self.firstNameVerification.verified:
            return False
        else:
            valid = True
            driving_licences = PersonDocument.objects.filter(person=self)
            if driving_licences.exists():
                for licence in driving_licences:
                    if not licence.verification.verified:
                        valid=False
                        break
            else:
                valid=False

            return valid

    def is_licence_uploaded(self):
        valid = False
        driving_licences = PersonDocument.objects.filter(person=self)
        if driving_licences.exists():
            valid=True
        return valid

    def is_profile_picture_uploaded(self):
        valid =True
        if not self.profilePicture:
            valid = False
        return valid

    def is_phone_number_added(self):
        valid =True
        if not self.phone:
            valid = False
        return valid

    def is_address_added(self):
        valid =True
        if not self.address:
            valid = False
        return valid

    def is_verified(self):
        admin_approved = False
        if self.approved:
            admin_approved = True
        else:
            admin_approved = False

renturcar/adminapp/views/dashboard_view.py
from django.views.generic import TemplateView

import datetime

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)
from api.models import Person , Vehicle

class DashboardView(TemplateView):

	template_name='dashboard/dashboard.html'
	
	def get_context_data(self,**kwargs):
		context = super(DashboardView, self).get_context_data(**kwargs)
		pending_users = []
		persons = Person.objects.all()
		context['total_users'] = len(persons)
		for person in persons:
			if not person.is_verified():
				pending_users.append(person)

		context['pending_users']=pending_users[:10]
		context['pending_users_count']=len(pending_users)

		pending_vehicles = []
		vehicles = Vehicle.objects.all()
		context['total_vehicles']=len(vehicles)
		for vehicle in vehicles:
			if not vehicle.is_verified():
				pending_vehicles.append(vehicle)

		context['pending_vehicles']=pending_vehicles[:10]
		context['pending_vehicles_count']=len(pending_vehicles)
		context['car_approved'] = len(vehicles)-len(pending_vehicles)
		return context

renturcar/adminapp/views/login_view.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.views.generic import TemplateView
from django.views import View
from django.conf import settings
from adminapp.forms.login_form import LoginForm
# from django.core.urlresolvers import reverse
#
# import requests
# import json
#

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)

class LoginView(View):

	template_name='login/login.html'
    
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return HttpResponseRedirect('dashboard/')
		else:
			form =LoginForm()
		return render(request, self.template_name,{"form":form})

	def post(self, request, *args, **kwargs):

		next2=request.GET.get("next")
		form = LoginForm(request.POST or None)
		print(request.user.is_authenticated())
		print('after post')
		if form.is_valid():
            # <process form cleaned data>
			print(request.user.is_authenticated())
			email=form.cleaned_data.get("email")
			password=form.cleaned_data.get("password")

			print('after is valid')
			user= authenticate(email=email,password=password)
			if user.is_admin:
				login(request,user)
			else:
				return HttpResponseRedirect('/admin')
			if next2:
				return HttpResponseRedirect(next2)
			return HttpResponseRedirect('dashboard/')
		return render(request, self.template_name, {'form': form})

class LogoutView(View):
		def get(self,request,*args,**kwargs):
			logout(request)
			return HttpResponseRedirect('/admin/')

renturcar/adminapp/templates/car/car.html
{% extends 'layout/main.html' %}
{% block content %}
    <div class="col-lg-12">
        <div class="row page-header" style="padding-bottom: 0;">
            <div class="col-md-6">
                <h2 class="">
                   {{ title }}
                </h2>
            </div>
            <div class="col-md-6" style="padding-top: 15px;text-align: right;">
                <a class="btn btn-primary " href="/admin/add-car">Add car</a>
            </div>
        </div>
        <div class="row" style="margin-bottom: 5px;">
            <div class="col-md-12">
                <ul class="nav nav-tabs">
                  <li {% if type == 'all' %}class="active" {% endif %}><a href="/admin/car/all"><i class="fa fa-car"></i> All</a></li>
                  <li {% if type == 'pending' %}class="active" {% endif %}><a href="/admin/car/pending"><i class="fa fa-clock"></i> Pending</a></li>
                  <li {% if type == 'approved' %}class="active" {% endif %}><a href="/admin/car/approved"><i class="fa fa-check"></i> Approved</a></li>
                </ul>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Licence plate</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>year</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for car in vehicles %}
                    <tr>
                        <td>{{ car.id }}</td>
                        <td>{{ car.licensePlate }}</td>
                        <td>{{ car.make }}</td>
                        <td>{{ car.model }}</td>
                        <td>{{ car.year }}</td>
                        <td>
                            <a href="/admin/car/details/{{ car.id }}">
                                <i class="fa fa-car"></i>
                            </a>
                            <a href="/admin/delete-car/{{ car.id }}">
                                <i style="color:red;" class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

renturcar/adminapp/templates/car/delete_confirm.html
{% extends "layout/main.html" %}
{% block content %}
<div class="col-lg-12">
        <div class="row page-header" style="padding-bottom: 0;">
            <div class="col-md-12">
                <h2 class="">
                    Delete Car
                </h2>
            </div>
        </div>
       <p>Are you sure you want to delete "{{ object.licensePlate }}"?</p>
       <form action="" method="post" novalidate>{% csrf_token %}

          <input type="submit" class='btn btn-danger' value="Confirm" />
          <a href="{{ view.get_success_url }}" class="btn btn-secondary">Cancel</a>
      </form>

</div>


{% endblock content %}

renturcar/adminapp/templates/car/form.html
{% extends 'layout/main.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                {{ title }}
            </h2>
        </div>
    </div>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

        <div class="masonry-item">
            <div class="bgc-white p-20 bd  col-md-12">
                <!-- <h6 class="c-grey-900">Add User</h6> -->
                <div class="mT-30">
                    <div class="row">
                        <div class="form-group col-md-12">
                           <label for="id_user">User</label>
                           <select class="form-control" name="user" id="id_user">
                               {% for person in persons %}
                                <option value="{{ person.id }}">{{ person.firstName }} {{ person.lastName }}</option>
                               {% endfor %}
                           </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                           <label for="id_bodytype">Body Type</label>
                           <select class="form-control" name="bodytype" id="id_bodytype">
                               {% for bodytype in bodytypes %}
                                <option value="{{ bodytype.id }}">{{ bodytype.name }}</option>
                               {% endfor %}
                           </select>
                        </div>
                        <div class="form-group col-md-6">
                           <label for="id_location">location</label>
                           <input type="text" placeholder="location of vehicle" class="form-control" id="id_location" name="location">
                           <input type="hidden" id="street_number" name="street_number"/>
                            <input type="hidden" id="route" name="route"/>
                            <input type="hidden" id="locality" name="locality" />
                            <input type="hidden" id="country" name="country" />
                            <input type="hidden" id="postal_code" name="postal_code"/>
                        </div>

                    </div>
                    <div class="row">

                        <div class="form-group col-md-6">
                           <label for="id_price">Price</label>
                           <input type="text" placeholder="Rent amount" class="form-control" id="id_price" name="price">
                        </div>
                        <div class="form-group col-md-6">
                           <label for="id_make">Make</label>
                           <select class="form-control" name="make" id="id_make">
                                <option value="Toyota">Toyota</option>
                                <option value="Subaru">Subaru</option>
                                <option value="Honda">Honda</option>
                           </select>
                        </div>

                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                           <label for="id_model">Model</label>
                           <select class="form-control" name="model" id="id_model">
                                <option value="WRX">WRX</option>
                                <option value="Tundra">Tundra</option>
                                <option value="Corolla">Corolla</option>
                                <option value="Land Cruiser">Land Cruiser</option>
                                <option value="Camry">Camry</option>
                                <option value="Highlander">Highlander</option>
                                <option value="RAV4">RAV4</option>
                                <option value="Avalon">Avalon</option>
                                <option value="Accord">Accord</option>
                                <option value="Civic">Civic</option>
                                <option value="Pilot">Pilot</option>
                                <option value="Fit">Fit</option>
                                <option value="Insight">Insight</option>
                                <option value="Legacy">Legacy</option>
                                <option value="Impreza">Impreza</option>
                                <option value="Outback">Outback</option>
                           </select>
                        </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                           <label for="id_licence">Licence plate</label>
                           <input type="text" placeholder="Licence plate no." class="form-control" id="id_licence" name="licence">
                      </div>
                      <div class="form-group col-md-6">
                           <label for="id_year">Year</label>
                           <input type="text" placeholder="Year" class="form-control" id="id_year" name="year">
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                           <label for="id_kilometer">Kilometer</label>
                           <input type="text" placeholder="Kilometer" class="form-control" id="id_kilometer" name="kilometer">
                      </div>
                      <div class="form-group col-md-6">
                           <label for="id_color">Color</label>
                           <input type="text" placeholder="Color" class="form-control" id="id_color" name="color">
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                           <label for="id_photo">Image</label>
                           <input type="file" class="form-control" id="id_photo" name="photo">
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                           <label for="id_summary">Summary</label>
                           <textarea class="form-control" id="id_summary" name="summary"></textarea>
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                           <label for="id_3f">3f insurance</label>
                           <input type="file" class="form-control" id="id_3f" name="finsurance">
                      </div>
                      <div class="form-group col-md-6">
                           <label for="id_pf">private insurance</label>
                           <input type="file" class="form-control" id="id_pf" name="pinsurance">
                      </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ view.get_success_url }}" class="btn btn-default">Cancel
                        </a>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </form>
    <script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        //administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('id_location')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        console.log(place);

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYgZJnLLT3iTGQcaCTd-S3z-V9d-ywors&libraries=places&callback=initAutocomplete"></script>
{% endblock %}