renturcar/adminapp/urls.py
from django.conf.urls import url
from views.login_view import LoginView
from .views.login_view import LogoutView
from .views.dashboard_view import DashboardView
from .views.admin_view import AdminCreate,AdminList,AdminDelete,AdminUpdate,AdminProfileUpdate,AdminPasswordChange
from django.contrib.auth.decorators import login_required
from .views.user_view import UserView,UserDetailView,UserApprove,UserDelete,UserCreateView
from .views.car_view import CarView,CarDetailView,CarApprove,CarDelete,CarCreateView
from .views.report_view import ReportCarView,ReportDailyUpdateView
urlpatterns = [

    # url(r'^admin/', admin.site.urls),
    url(r'^$',  LoginView.as_view()),
    url(r'^logout/$',  LogoutView.as_view(),name="logout"),
    url(r'^dashboard/$',login_required(DashboardView.as_view()),name="dashboard"),
    url(r'^add-admin/$',login_required(AdminCreate.as_view()),name="add-admin"),
    url(r'^list-admin/$',login_required(AdminList.as_view()),name="list-admin"),
    url(r'^delete-admin/(?P<id>[0-9]+)/$',login_required(AdminDelete.as_view()),name="delete-admin"),
    url(r'^update-admin/(?P<id>[0-9]+)/$',login_required(AdminUpdate.as_view()),name="update-admin"),
    url(r'^update-profile/$',login_required(AdminProfileUpdate.as_view()),name="update-profile"),
    url(r'^change-password/$',login_required(AdminPasswordChange.as_view()),name="change-password"),

    # user
    url(r'^user/(?P<status>[\w-]+)/$',login_required(UserView.as_view()),name="user"),
    url(r'^user/details/(?P<id>[0-9]+)/$',login_required(UserDetailView.as_view()),name="user-details"),
    url(r'^user-approve/$',login_required(UserApprove.as_view()),name="user-approve"),
    url(r'^delete-user/(?P<id>[0-9]+)/$', login_required(UserDelete.as_view()),name="delete-user"),
    url(r'^add-user/$',login_required(UserCreateView.as_view()),name="add-user"),
    #car
    url(r'^car/(?P<status>[\w-]+)/$',login_required(CarView.as_view()),name="car"),
    url(r'^car/details/(?P<id>[0-9]+)/$',login_required(CarDetailView.as_view()),name="car-details"),
    url(r'^car-approve/$',login_required(CarApprove.as_view()),name="car-approve"),
    url(r'^delete-car/(?P<id>[0-9]+)/$', login_required(CarDelete.as_view()),name="delete-car"),
    url(r'^add-car/$',login_required(CarCreateView.as_view()),name="add-car"),
    #report
    url(r'^report-car-view/$',login_required(ReportCarView.as_view()),name="report-car-view"),
    url(r'^report-daily-update/$',login_required(ReportDailyUpdateView.as_view()),name="report-daily-update"),
]

renturcar/renturcar/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from api.views import *
from django.conf import settings
urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include('adminapp.urls')),
    url(r'^login$', login_view),
    url(r'^logout$', logout_view),
    url(r'^signup/?$', signup_view),

    # User views.
    url(r'^user/?$', user_views),
    url(r'^user/(inbox)/?$', user_views),
    url(r'^user/inbox/with/(\w*)', user_view_inbox_direct),
    url(r'^user/message/reply', message_reply),
    url(r'^user/(cars)/?$', user_views),
    url(r'^user/(history)/?$', user_views),
    url(r'^user/verify/(.*)/(.*)?$', user_view_verify),
    url(r'^user/booking-inbox/(\w*)', user_booking_inbox),

    # User Account views.
    url(r'^user/account/?$', user_account_index_view),
    url(r'^user/account/picture/?$', user_account_picture_view),
    url(r'^user/account/licence/?$', user_account_license_view),
    url(r'^user/account/(payment)/?$', user_account_views),
    url(r'^user/account/(payout)/?$', user_account_views),
    url(r'^user/account/(security)/?$', user_account_views),
    url(r'^user/account/(cancel)/?$', user_account_views),
    url(r'^user/account/security/change-password/?$', change_password_view),
    url(r'^confirmation/?$', user_account_confirmation_view),
    url(r'^terms-and-conditions/?$', terms_and_conditions_view),




    url(r'^car/(\w*)/request/(\w*)?/?(\w*)?', car_request_view),
    url(r'^car/(\w*)/a/(.*)/(.*)', car_availability),
    url(r'^car/(\w*)/?.*', car_view, name='car_view'),

    url(r'^message', send_message_view),

    url(r'^search$', search_view, name='search_view'),

    url(r'^new$', new_listing_view, name='new_listing_view'),
    url(r'^requirements$', requirements_view),
    url(r'^contact/$', contact_view, name='contact_view'),


    url(r'^$', home_view),




]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

renturcar/adminapp/forms/login_form.py
from django import forms

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)

User=get_user_model()

class LoginForm(forms.Form):

		email=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required': False}))
		password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','required': False}))

		def clean(self, *args, **kwargs):

			email=self.cleaned_data.get('email')
			password=self.cleaned_data.get('password')

			if email and password:
				user = authenticate(email=email,password=password)
				if not user:
					raise forms.ValidationError('User does not exist')
				if not user.is_active:
					raise forms.ValidationError('Sorry you are not active')
				if not user.check_password(password):
					raise forms.ValidationError('Incorrect password')
				if not user.is_admin:
					raise forms.ValidationError('Not authorize to login')
			return super(LoginForm,self).clean(*args,**kwargs)

renturcar/api/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField()
    contact_email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)

renturcar/adminapp/views/car_view.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView,DeleteView
from django.http import JsonResponse
import datetime
import json
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
    )
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from api.models import Person , Vehicle , PersonDocument,VehicleDocument,BodyType,CostPerDay,Address,VehiclePhoto
from django.shortcuts import render,redirect

class CarCreateView(TemplateView):
    template_name = 'car/form.html'

    def address_get_or_create(self,lineOne,city,country,post_code):
        address_obj = None
        address = Address.objects.filter(lineOne=lineOne,lineTwo=city,country=country,postCode=post_code)
        if address.exists():
            address_obj = address.first()
        else:
            address_obj = Address()
            address_obj.lineOne=lineOne
            address_obj.lineTwo=city
            address_obj.country=country
            address_obj.postCode=post_code
            address_obj.save()
        return address_obj

    def get(self,request,*args,**kwargs):
        context={}
        context['title']='Add car'
        context['bodytypes']=BodyType.objects.all()
        context['persons']= Person.objects.all()
        return render(request,self.template_name,context)

    def post(self,request,*args,**kwargs):
        person = request.POST.get('user')
        body_type = request.POST.get('bodytype')
        location = request.POST.get('location')
        price = request.POST.get('price')
        make = request.POST.get('make')
        model = request.POST.get('model')
        licenceplate = request.POST.get('licence')
        year = request.POST.get('year')
        kilo = request.POST.get('kilometer')
        summary = request.POST.get('summary')
        color = request.POST.get('color')
        photo=request.FILES['photo']
        insurance_3fs=request.FILES['finsurance']
        private_insurane = request.FILES['pinsurance']

        v = Vehicle()
        v.make=make
        v.model=model
        v.year=year
        v.licensePlate=licenceplate
        v.colour=color
        v.comments=summary
        v.bodyType_id=body_type
        v.owner_id=person
        c = CostPerDay()
        c.rentalCost = price
        c.commissionCost = 0.0
        c.save()
        v.defaultCost = c

        lineOne=[]
        lineTwo=''
        country=''
        postal_code=''
        if 'street_number' in request.POST:
            street_number = request.POST['street_number']
            lineOne.append(street_number)

        if 'route' in request.POST:
            route = request.POST['route']
            lineOne.append(route)

        line1 = ''
        line1 = ' '.join(lineOne)
        if 'locality' in request.POST:
            lineTwo = request.POST['locality']
        if 'country' in request.POST:
            country = request.POST['country']
        if 'postal_code' in request.POST:
            postal_code = request.POST['postal_code']

        v.address = self.address_get_or_create(line1,lineTwo,country,postal_code)
        v.rules = ''
        v.minRentDays = 0
        v.maxRentDays = 0
        v.advanceNotice = 0
        v.preparationTime = 0
        v.save()
        vp = VehiclePhoto()
        vp.photo = photo
        vp.vehicle = v
        vp.save()

        vd= VehicleDocument(vehicle=v,document=private_insurane)
        vd.save()

        vi= VehicleDocument(vehicle=v,document=insurance_3fs)
        vi.save()

        return redirect('/admin/car/details/'+str(v.id)+'/')

    def get_success_url(self):
        return reverse('car',kwargs={'status':'all'})

class CarView(TemplateView):

    template_name='car/car.html'
    def get_context_data(self,**kwargs):
        status = kwargs.get('status')
        context = super(CarView, self).get_context_data(**kwargs)
        vehicles = Vehicle.objects.all()
        context['total_cars'] = len(vehicles)
        if status == 'pending':
            pending_vehicles = []
            context['title']= 'Pending cars'
            context['type']='pending'
            for vehicle in vehicles:
                if not vehicle.is_verified():
                    pending_vehicles.append(vehicle)
            context['vehicles']=pending_vehicles

        elif status == 'approved':
            context['title'] = 'Approved Cars'
            approved_cars = []
            for vehicle in vehicles:
                if vehicle.is_verified():
                    approved_cars.append(vehicle)
            context['vehicles']=approved_cars
            context['type']='approved'
        else:
            context['title'] = 'All Cars'
            context['vehicles']=vehicles
            context['type']='all'
        return context

class CarDetailView(TemplateView):
    template_name = "car/details.html"

    def get_context_data(self, **kwargs):
        vehicle_id = kwargs.get('id')
        context = super(CarDetailView, self).get_context_data(**kwargs)
        context['vehicle']= Vehicle.objects.get(id=vehicle_id)
        context['documents']= VehicleDocument.objects.filter(vehicle_id=vehicle_id)
        return context


class CarApprove(CreateView):
    def post(self, request, *args, **kwargs):
            car_id = request.POST.get('car_id')

            documents = VehicleDocument.objects.filter(vehicle_id=car_id)
            for document in documents:
                document.verification.verified = True
                document.verification.save()

            response_data={}
            response_data['status']=True
            return HttpResponse(json.dumps(response_data), content_type="application/json")

class CarDelete(DeleteView):
    template_name='car/delete_confirm.html'
    def get_object(self,**kwargs):
        return Vehicle.objects.get(id=self.kwargs['id'])

    def get_success_url(self):
        return reverse('car',kwargs={'status':'all'})

renturcar/adminapp/views/login_view.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.views.generic import TemplateView
from django.views import View
from django.conf import settings
from adminapp.forms.login_form import LoginForm
# from django.core.urlresolvers import reverse
#
# import requests
# import json
#

from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout
	)

class LoginView(View):

	template_name='login/login.html'
    
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return HttpResponseRedirect('dashboard/')
		else:
			form =LoginForm()
		return render(request, self.template_name,{"form":form})

	def post(self, request, *args, **kwargs):

		next2=request.GET.get("next")
		form = LoginForm(request.POST or None)
		print(request.user.is_authenticated())
		print('after post')
		if form.is_valid():
            # <process form cleaned data>
			print(request.user.is_authenticated())
			email=form.cleaned_data.get("email")
			password=form.cleaned_data.get("password")

			print('after is valid')
			user= authenticate(email=email,password=password)
			if user.is_admin:
				login(request,user)
			else:
				return HttpResponseRedirect('/admin')
			if next2:
				return HttpResponseRedirect(next2)
			return HttpResponseRedirect('dashboard/')
		return render(request, self.template_name, {'form': form})

class LogoutView(View):
		def get(self,request,*args,**kwargs):
			logout(request)
			return HttpResponseRedirect('/admin/')

renturcar/api/templates/confirmation.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">
    <head>
        {% include "header_scripts.html" %}
        <title>RentUrCar</title>
    </head>

    <body>
        {% include "navbar.html" %}
            <div class="alert alert-success" role="alert" style="margin-top: 1px;text-align: center;">
               {% if messages %}
                    {% for message in messages %}
                       {{ message }} </br>
                    {% endfor %}
                {% endif %}
            </div>
        {% include "footer.html" %}
        {% include "footer_scripts.html" %}
    </body>
</html>

renturcar/api/templates/contact.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">
    <head>
        {% include "header_scripts.html" %}
        <title>SwiftRydes - Contact</title>
    </head>

    <body>
        {% include "navbar.html" %}
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 contact-form">
              <h1>Contact us</h1>
              <p>Humblebrag scenester meditation, mustache tattooed narwhal bespoke mixtape kinfolk kogi meggings gastropub. Retro deep v ramps, tbh umami copper mug church-key green juice godard. Jean shorts chia flexitarian tofu, hell of hoodie ennui direct trade readymade. Salvia snackwave lyft craft beer, hoodie gluten-free portland YOLO vegan tbh butcher. Pop-up chillwave small batch chambray freegan, mlkshk health goth subway tile. Kombucha marfa vaporware ennui hella swag. Echo park kinfolk pop-up, shoreditch flannel hammock godard lo-fi live-edge 3 wolf moon cronut slow-carb.</p>
              <br/>
              <form role="form" action="" method="post">

                {% csrf_token %}
                <div class="form-group" id="contact-form-group">
                  <label for="contact_name">Full name</label>
                  <input type="text" class="form-control" id="id_contact_name" name="contact_name" placeholder="Full name">
                </div>
                <div class="form-group" id="contact-form-group">
                  <label for="contact_email">Email</label>
                  <input type="email" class="form-control" id="id_contact_email" name="contact_email" placeholder="Email"/>
                </div>

                <div class="form-group" id="contact-form-group">
                  <label for="content">Message</label>
                  <textarea class="form-control" id="id_content" name="content" rows="8" style="width: 100%;"></textarea>
                </div>

                <button type="submit" class="btn custom-button">Submit</button>
              </form>
            </div>
            <div class="col-md-4"></div>
          </div>
        </div>
    </body>

    {% include "footer.html" %}
    {% include "footer_scripts.html" %}

</html>

renturcar/api/templates/footer.html
<footer class="footer">
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <a href="#" class="footer-links">Blog</a>
                <a href="#" class="footer-links">Terms &amp; Conditions</a>
                <a href="/contact/" class="footer-links">Contact</a>
                <a href="#" class="footer-links">
        <i class="fa fa-facebook-official" aria-hidden="true"></i>
    </a>
                <a href="#" class="footer-links">
        <i class="fa fa-twitter-square" aria-hidden="true"></i>
    </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <p class="text-muted" style="margin: 20px 0px; text-align: center">
                    SwiftRydes &copy; 2017. All rights reserved.
                </p>
            </div>
        </div>
    </div>
</footer>

renturcar/api/templates/footer_scripts.html
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>

</script>
<script src="http://d3js.org/d3.v3.js"></script>

renturcar/api/templates/header_scripts.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">

{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/application.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css">



<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

renturcar/api/templates/home.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">

<head>
    {% include "header_scripts.html" %}
    <title>SwiftRydes</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="full">
        <div class="hero-section">
            <h2>Rent a car with us</h2>
            <form action="/search" method="get">
              
                <div class="form-content container" id="responsive_view_form">
                    <div>
                        <input name="q" hidden="hidden">
                    </div>
                    <div class="row" style="margin: 0 auto;text-align: center;">
                        <div id="homepage-search-input" class="col-sm-5 input-group">
                            <span class="input-group-addon">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
                            <input name="b" class="form-control" placeholder="Type of Vehicle" aria-describedby="basic-addon3" type="text">
                        </div>
                        <div id="homepage-search-input" class="col-sm-5 input-group">
                            <span class="input-group-addon" id="basic-addon1">
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                            </span>
                            <input name="l" id="location" class="form-control" placeholder="Location/Country/City/PostCode" aria-describedby="basic-addon1" type="text ">
                            <input type="hidden" id="street_number" name="street_number"/>
                            <input type="hidden" id="route" name="route"/>
                            <input type="hidden" id="locality" name="locality" />
                            <input type="hidden" id="country" name="country" />
                            <input type="hidden" id="postal_code" name="postal_code"/>
                        </div>
{#                        <div id="homepage-search-input" class="col-sm-4 input-group">#}
{#                            <span class="input-group-addon" id="basic-addon1">#}
{#                <span class="glyphicon glyphicon-calendar " aria-hidden="true "></span>#}
{#                            </span>#}
{#                            <input name="d" class="form-control" placeholder="Date" aria-describedby="basic-addon2" type="date">#}
{#                        </div>#}

                            <button  id="search-button-home-screen" type="submit" class="btn custom-button col-sm-2 input-group" role="button ">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="container how-it-works ">
            <h2>How it works?</h2>
            <p>Apple pie cake oat cake croissant pastry biscuit caramels candy. Sweet roll chocolate danish cotton candy sesame snaps chupa chups. Bear claw chupa chups marshmallow gummi bears bonbon chocolate cake brownie cookie. Bonbon fruitcake liquorice muffin cake jelly-o gummies biscuit. Sugar plum gummies donut jujubes chupa chups pie cupcake cupcake bonbon. Macaroon gummies cotton candy pastry sweet caramels macaroon oat cake. Icing cake pastry. Pudding pudding lemon drops. Sugar plum sweet cupcake. Chocolate jelly-o bear claw wafer dessert. Sesame snaps caramels marzipan. Carrot cake caramels sugar plum powder. Chocolate oat cake chocolate cake.</p>
        </div>
    </div>
    <div class="container-fluid customer-quote ">
        <p>“I love this service. Sugar plum sweet cupcake. Chocolate jelly-o bear claw wafer dessert.”</p>
    </div>
</body>
<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        //administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('location')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        console.log(place);

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>
{% include "footer.html" %}
{% include "footer_scripts.html" %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYgZJnLLT3iTGQcaCTd-S3z-V9d-ywors&libraries=places&callback=initAutocomplete"></script>

</html>

renturcar/api/templates/login.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">
    <head>
        {% include "header_scripts.html" %}
        <title>RentUrCar</title>
    </head>

    <body>
        {% include "navbar.html" %}
        {% if error %}
        <div class="alert alert-danger" role="alert" style="margin-top: 1px;text-align: center;">{{ error }}</div>
        {% endif %}
        <div class="container">
            <div>
              <form action="/login?next={{ goto }}" method="POST" class="form-signin" style="max-width: 400px; margin: 0 auto;" autocomplete="on">
                  <h2 class="form-signin-heading">Please login</h2>
                  {% csrf_token %}
                  <!-- <input type="hidden" name="redirect" value="/research/"> -->
                  <div class="form-group {% if x %}has-error{% endif %}">
                    <label for="x" class="sr-only">E-mail</label>
                    <input id="x" type="email" name="x" class="form-control" placeholder="E-mail"/ required autofocus>

                  </div>
                  <div class="form-group {% if password %}has-error{% endif %}">
                    <label for="password" class="sr-only">Password</label>
                    <input id="y" type="password" name="y" class="form-control" placeholder="Password"/ required>
                  </div>

                  <div class="actions">
                      <input type="submit" class="btn custom-button btn-block" id="fiftypixel-height">
                  </div>
                </form>
            </div>
        </div>

        {% include "footer.html" %}
        {% include "footer_scripts.html" %}
    </body>
</html>

renturcar/api/templates/requirements.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">
    <head>
        {% include "header_scripts.html" %}
        <title>RentUrCar</title>
        </head>

        <body>
            {% include "navbar.html" %}

            <div class="container">
                <h2>{{ title }}</h2>
                <div class="col-md-12">
                <h3>Review Renters Requirements</h3>
                <hr>
                <div class="requirement-disclaimer"><h4>All renters must accept the following requirements to book:</h4></div>
                <div class="requirement-group">
                  <div class="requirement-status-tick"><span class="fa fa-check-circle" style="color: #2F7748;"></span></div>
                  <div class="requirement-name"><p>Requirement 1</p></div>
                </div>
                <div class="requirement-group">
                  <div class="requirement-status-tick"><span class="fa fa-check-circle" style="color: #2F7748;"></span></div>
                  <div class="requirement-name"><p>Requirement 2</p></div>
                </div>
                <div class="requirement-group">
                  <div class="requirement-status-tick"><span class="fa fa-check-circle" style="color: #2F7748;"></span></div>
                  <div class="requirement-name"><p>Requirement 3</p></div>
                </div>
                <div class="requirement-group">
                  <div class="requirement-status-tick"><span class="fa fa-check-circle" style="color: #2F7748;"></span></div>
                  <div class="requirement-name"><p>Requirement 4</p></div>
                </div>
              </div>


              <div class="container">
                <div class="row">
                  <div class="col-sm-6"id="additional-requirement">
                    <label>Add additional requirements</label>
                    <textarea class="form-control" rows="2" placeholder="Type any additional requirements"></textarea>
                    <button class="btn custom-button" id="add-requirement-button" type="submit">Add</button>
                  </div>
                </div>

                <a href="#"><button class="btn custom-button submit-button-requirements">Submit</button></a>

              </div>

            </div>

        {% include "footer.html" %}
        {% include "footer_scripts.html" %}
    </body>
</html>

renturcar/api/templates/terms_and_conditions.html
<!DOCTYPE html>
<html lang="en" style="position: relative; min-height:100%">
    <head>
        {% include "header_scripts.html" %}
        <title>RentUrCar</title>
    </head>

    <body>
        {% include "navbar.html" %}
        <p class="col-md-8 col-md-offset-2" style="margin-top:5%;text-align: justify">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with
            desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
        {% include "footer.html" %}
        {% include "footer_scripts.html" %}
    </body>
</html>